### ISSUE TITLE
System.NullReferenceException at start Xamarin Droid App

### ISSUE THREAD

**Issue by sergio11** [martijn00/MvxForms#1]
First of all, thanks for example.

But I have a problem integrating your example with other packages that require initialization on each platform (in this case Android). For example, I installed the Acr.UserDialogs package version 6.4.1.

The only thing I modify is the main activity after calling based on the super class I initialize the plugin.

```
namespace MvxForms.Droid
{
    [Activity(Label = "MvxForms.Droid", Icon = "@drawable/icon", Theme = "@style/MyTheme", ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
    public class MainActivity : MvxFormsAppCompatActivity
    {
        protected override void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;
            UserDialogs.Init(this);
			PullToRefreshLayoutRenderer.Init();
			XFGloss.Droid.Library.Init(this, bundle);
			//Initializing FFImageLoading
			CachedImageRenderer.Init();

        }
    }
}
```

Then in the PCL register the instance as a singleton in the IOC container:

```
namespace MvxForms.Core
{
    public class CoreApp : MvvmCross.Core.ViewModels.MvxApplication
    {
        public override void Initialize()
        {
            CreatableTypes()
                .EndingWith("Service")
                .AsInterfaces()
                .RegisterAsLazySingleton();

            Mvx.RegisterSingleton<IUserDialogs>(() => UserDialogs.Instance);

            RegisterAppStart<ViewModels.MvxFormsViewModel>();
        }
    }
}
```

Modify your example ViewModel to request the injection of the service.

```
namespace MvxForms.Core.ViewModels
{
    public class MvxFormsViewModel : MvxViewModel
    {

        protected readonly IUserDialogs _userDialogs;

        public MvxFormsViewModel(IUserDialogs userDialogs)
        {
            _userDialogs = userDialogs;
        }
        
        public override Task Initialize()
        {
            //TODO: Add starting logic here
		    
            return base.Initialize();
        }
        
        public IMvxCommand ResetTextCommand => new MvxCommand(ResetText);
        private void ResetText()
        {
            Text = "Hello MvvmCross";
        }

        private string _text = "Hello MvvmCross";
        public string Text
        {
            get { return _text; }
            set { SetProperty(ref _text, value); }
        }
    }
}
```

When launching the application, get the following error:

![captura de pantalla 2017-10-02 a las 12 23 56](https://user-images.githubusercontent.com/6996211/31073536-9a58c324-a76c-11e7-91d8-27a15155792a.png)

![captura de pantalla 2017-10-02 a las 12 24 28](https://user-images.githubusercontent.com/6996211/31073551-a98093b8-a76c-11e7-8982-84e7e1c4ee17.png)

This is the trace of the error that I see by console:

```
mvx:Warning:  1.39 Exception masked MvxException: Failed to construct and initialize ViewModel for type MvxForms.Core.ViewModels.MvxFormsViewModel from locator MvxDefaultViewModelLocator - check InnerException for more information
	  at MvvmCross.Core.ViewModels.MvxViewModelLoader.LoadViewModel (MvvmCross.Core.ViewModels.MvxViewModelRequest request, MvvmCross.Core.ViewModels.IMvxBundle savedState, MvvmCross.Core.ViewModels.IMvxViewModelLocator viewModelLocator) [0x00020] in D:\git\MvvmCross\MvvmCross\Core\Core\ViewModels\MvxViewModelLoader.cs:73 
```

Could you give me some tips on how I can solve this problem? Thank you very much in advance.

**Comment by martijn00** [comment]
In your setup.cs on Android do 

```
protected override void InitializePlatformServices()
{
            UserDialogs.Init(() => Mvx.Resolve<IMvxAndroidCurrentTopActivity>().Activity);
}
```

Or call `UserDialogs.Init(this);` from the splashscreen since that is your first activity.

**Comment by ScorpDiesel** [comment]
@martijn00 :

I've followed @sergio11's footsteps and I've done what he's done.  After following your instructions, I get the below error when deploying.  I tried adding `UserDialogs.Init(this);` to the splashscreenview and adding `UserDialogs.Init(() => Mvx.Resolve<IMvxAndroidCurrentTopActivity>().Activity);` to `InitializePlatformServices()` in the Android Setup(): 

`10-17 18:40:32.012 E/mono    (15382): Unhandled Exception:
10-17 18:40:32.012 E/mono    (15382): MvvmCross.Platform.Exceptions.MvxIoCResolveException: Failed to resolve type MvvmCross.Droid.Platform.IMvxAndroidActivityLifetimeListener
10-17 18:40:32.012 E/mono-rt (15382): [ERROR] FATAL UNHANDLED EXCEPTION: MvvmCross.Platform.Exceptions.MvxIoCResolveException: Failed to resolve type MvvmCross.Droid.Platform.IMvxAndroidActivityLifetimeListener
10-17 18:40:32.016 D/Mono    (15382): Unloading image System.Threading.Tasks.dll [0x76365fa800].
10-17 18:40:32.017 D/Mono    (15382): Image addref System.Threading.Tasks[0x7635d69000] -> System.Threading.Tasks.dll[0x763654e800]: 6
10-17 18:40:32.017 D/Mono    (15382): Config attempting to parse: 'System.Threading.Tasks.dll.config'.
10-17 18:40:32.018 D/Mono    (15382): Config attempting to parse: '/usr/local/etc/mono/assemblies/System.Threading.Tasks/System.Threading.Tasks.config'.
10-17 18:40:32.018 D/Mono    (15382): Assembly Ref addref SparqDigital.Nvdeus.Mobile.Core[0x7637e9e700] -> System.Threading.Tasks[0x7636542380]: 4
10-17 18:40:32.019 I/TMSDISP (15382): AcsAndroidVirtualDisplayIntfImpl::~AcsAndroidVirtualDisplayIntfImpl - Enter
10-17 18:40:32.019 I/TMSDISP (15382): AcsAndroidVirtualDisplayIntfImpl::~AcsAndroidVirtualDisplayIntfImpl - Enter2
10-17 18:40:32.019 I/TMSDISP (15382): AcsAndroidVirtualDisplayIntfImpl::~AcsAndroidVirtualDisplayIntfImpl - mSource2
10-17 18:40:32.019 I/TMSDISP (15382): AcsAndroidVirtualDisplayIntfImpl::~AcsAndroidVirtualDisplayIntfImpl - Exit`

Any help would be greatly appreciated.

**Comment by ScorpDiesel** [comment]
Got it to work by looking at [this](https://www.symbolsource.org/Public/Metadata/NuGet/Project/MvvmCross.HotTuna.MvvmCrossLibraries/3.5.0/Release/MonoAndroid,Version%3Dv0.0/Cirrious.MvvmCross.Droid/Cirrious.MvvmCross.Droid/Platform/MvxAndroidSetup.cs?ImageName=Cirrious.MvvmCross.Droid) and deducing some things and adding this to the Setup.cs in Android:


```
protected override void InitializePlatformServices()
        {
            InitializeLifetimeMonitor();
            Mvx.RegisterSingleton<IMvxAndroidGlobals>(this);

            var intentResultRouter = new MvxIntentResultSink();
            Mvx.RegisterSingleton<IMvxIntentResultSink>(intentResultRouter);
            Mvx.RegisterSingleton<IMvxIntentResultSource>(intentResultRouter);

            var viewModelTemporaryCache = new MvxSingleViewModelCache();
            Mvx.RegisterSingleton<IMvxSingleViewModelCache>(viewModelTemporaryCache);

            var viewModelMultiTemporaryCache = new MvxMultipleViewModelCache();
            Mvx.RegisterSingleton<IMvxMultipleViewModelCache>(viewModelMultiTemporaryCache);

            UserDialogs.Init(() => Mvx.Resolve<IMvxAndroidCurrentTopActivity>().Activity);
        }

        protected override void InitializeLifetimeMonitor()
        {
            var lifetimeMonitor = CreateLifetimeMonitor();
            Mvx.RegisterSingleton<IMvxAndroidActivityLifetimeListener>(lifetimeMonitor);
            Mvx.RegisterSingleton<IMvxAndroidCurrentTopActivity>(lifetimeMonitor);
            Mvx.RegisterSingleton<IMvxLifetime>(lifetimeMonitor);
        }
```
