### ISSUE TITLE
Currently now out of date

### ISSUE THREAD

**Issue by llevera** [martijn00/MvxForms#2]
MvvmCross is now up to 5.3.1, which introduced a number of namespace changes.
As such, this project is no longer an up to date guide how to set up MvvmCross for Forms as someone doing so will naturally be binding to the latest.

If you would like to open up to pull requests, I have a branch of this project that updates to 5.3.1 and fixes a number of small issues that come out of this.

On a separate note, the content at https://www.mvvmcross.com/documentation/platform/forms/xamarin-forms?scroll=435/ (https://github.com/MvvmCross/MvvmCross/blob/master/docs/_documentation/platform/forms/xamarin-forms.md) is unfortunately also out of date (even compare to the master version of this project). I could possibly have a go at patching this up.

**Comment by martijn00** [comment]
Thanks for the issue! It would still be awesome if you could update the documentation!
