### ISSUE TITLE
SetFlags must be called before init.

### ISSUE THREAD

**Issue by anee146** [martijn00/MvxForms#5]
1) Clone  project from the below mentioned repository.
     https://github.com/martijn00/MvxForms
2) Update nuget packages to the latest one one
     Xamarin.Forms to 2.5.0 or above.
3) Set android project as start project.
4) Add the below mentioned line in MainActivity.cs before Xamarin.Forms.Init
     global::Xamarin.Forms.Forms.SetFlags("FastRenders_Experimental").
5) Build and run the application.

Expected behaviour.
    Application should run properly.

Actual behaviour.
    Application throws an exception says that, SetFlags must be called before Init.

A sample xamarin forms project works properly with the FastRenderer features (Not contain MvvmCross). But if applying the same in Xamarin forms with MvvmCross app fails.

Could you please help me on this?
1) Clone  project from the below mentioned repository.
     https://github.com/martijn00/MvxForms
2) Update nuget packages to the latest one one
     Xamarin.Forms to 2.5.0 or above.
3) Set android project as start project.
4) Add the below mentioned line in MainActivity.cs before Xamarin.Forms.Init
     global::Xamarin.Forms.Forms.SetFlags("FastRenders_Experimental").
5) Build and run the application.

Expected behaviour.
    Application should run properly.

Actual behaviour.
    Application throws an exception says that, SetFlags must be called before Init.

A sample xamarin forms project works properly with the FastRenderer features (Not contain MvvmCross). But if applying the same in Xamarin forms with MvvmCross app fails.

Could you please help me on this?

**Comment by goldnarms** [comment]
+1

**Comment by martijn00** [comment]
Please file this against the official MvvmCross repo.

**Comment by boletus151** [comment]
@anee146 this order worked for me:

global::Xamarin.Forms.Forms.SetFlags("FastRenderers_Experimental");
global::Xamarin.Forms.Forms.Init(this, bundle);
AiForms.Dialogs.Dialogs.Init(this); //need to write here

 base.OnCreate(bundle);
