### ISSUE TITLE
Strange back button behaviour

### ISSUE THREAD

**Issue by ghost** [martijn00/MvxForms#7]
I encountered a strange issue, hopefully you know how to counter this:

- on Android, build and open the app
- close with the back button
- re-open by tapping the app icon or in the recents list
- press back button again

Instead of closing the app, a new (previous?) instance of the app pops up.

I have the same issue in my Forms app once I migrated to MvvmCross.Forms, but I don't see the same behaviour in the Playgrounds sample in the MvvmCross repo.

**Comment by martijn00** [comment]
Please file this against the official MvvmCross repo.
