### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by situssoft** [martijn00/MvxForms#8]
Hi,

I've just cloned this repo and built and run locally on both android simulator and a google pixel. In both cases the app starts and shows the splash screen then after a short delay crashes. I have not modified the code.

This is my first attempt to use Mvvmcross and Xamarin forms. All I get from the debugger is the following rather unhelpful exception.

Unhandled Exception:

System.ArgumentNullException: Value cannot be null.
Parameter name: source occurred

Can you advise how I might progress to a working solution?

**Comment by jaredballen** [comment]
@situssoft, did you ever resolve your issue with this? I am running into the same thing.

**Comment by ghost** [comment]
Same thing here.

**Comment by situssoft** [comment]
No, I didn't find a fix and I was unable to build the code from source control (which is a pet hate) so I've moved my project to Prism.

**Comment by rafaelnicolett** [comment]
Same problem here. Any suggestions?

**Comment by rafaelnicolett** [comment]
I discovered the solution for this problem, remove the class Setup and SplashScreen and change the MainActivity for like this:

```csharp
[Activity(Label` = "Sample", Icon = "@mipmap/icon", Theme = "@style/AppTheme",
              ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation,
              MainLauncher = true, LaunchMode = LaunchMode.SingleTask)]
    public class MainActivity : MvxFormsAppCompatActivity<MvxFormsAndroidSetup<CoreApp, App>, CoreApp, App>
    {
        protected override void OnCreate(Bundle bundle)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;
            base.OnCreate(bundle);
        }
    }
```

More details in [TipCalc Sample](https://github.com/MvvmCross/MvvmCross-Samples/tree/master/TipCalc)

**Comment by agat366** [comment]
Unfortunately, this is quite often thing with MvvmCross these days, when it just doesn't work out-of-box. So, lots of devs just choose other frameworks.

@rafaelnicolett, this is still not ideal solution as it considers no splash screen, which is barely acceptable for most of apps.

After some investigation I've found correct way to make it work (quite weird why there is no docs about that anywhere) (hello wasted 4 hours of my time):

            public class SplashScreen : MvxFormsSplashScreenAppCompatActivity<Setup, CoreApp, App>

The only trick here is setting `Theme = "@style/MainTheme"` to support `AppCompat` one, but all that is just up to the dev how to define it then...

**Comment by rafaelnicolett** [comment]
@agat366 Great observation, I know that my solution it's bad, but it's work for hour. 
Thank you for shared you solution with us. 👌

**Comment by rafaelnicolett** [comment]
@agat366 Great, it's work now perfect. Thank you 😊

**Comment by martijn00** [comment]
Fixed in https://github.com/martijn00/MvxForms/commit/c464e929d84e2193a788dbd7543f3b3b1541cb31
