### ISSUE TITLE
Droid Splashscreen and Setup classes are not correct - producing a crash when the Droid app starts

### ISSUE THREAD

**Issue by jameslavery-zz** [martijn00/MvxForms#9]
As discovered in https://github.com/martijn00/MvxForms/issues/8, the Setup and SplashScreen are not correct.

https://github.com/martijn00/MvxForms/blob/2a0d658d564f0b51e9bd14bec233968fad5469be/MvxForms.Droid/Setup.cs#L8

Should be:

`public class Setup : MvxFormsAndroidSetup<CoreApp, App>`

And the line:

https://github.com/martijn00/MvxForms/blob/2a0d658d564f0b51e9bd14bec233968fad5469be/MvxForms.Droid/SplashScreen.cs#L15

Should be:

` public class SplashScreen : MvxFormsSplashScreenActivity<Setup, CoreApp, App>`

**Comment by martijn00** [comment]
Fixed in https://github.com/martijn00/MvxForms/commit/c464e929d84e2193a788dbd7543f3b3b1541cb31
